### ISSUE TITLE
cannot VACUUM from within a transaction

### ISSUE THREAD

**Issue by farfromrefug** [nutiteq/mobile-sdk-scripts#1]
while running `python3 scripts/build_map_packages.py packages-carto.json france.mbtiles packages` i get an error for every package:
```
Package FR-N failed: cannot VACUUM from within a transaction
```
Don't you get that error from your side?

**Comment by farfromrefug** [comment]
I fixed it by removing that line 
https://github.com/nutiteq/mobile-sdk-scripts/blob/master/scripts/build_map_packages.py#L331

**Comment by mtehver** [comment]
Did not happen to me when using this script, but encountered something similar with another script. Should be fixed now by explicitly closing and then reopening the database files before doing VACUUM. Thus closing this.
